name: push-to-master
on:
  push:
    branches:
      - master
jobs:
  test-ray-master:
    runs-on: ubuntu-latest
    defaults:
      run:
        # `shell: bash -l {0}` - special way to activate modin environment
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          environment-file: requirements/requirements-no-engine.yml
          python-version: 3.8
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: install Ray nightly build
        run: pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
      - name: Conda environment
        run: |
          conda info
          conda list
      - run: sudo apt update && sudo apt install -y libhdf5-dev
      - name: Run Modin tests
        run: |
          pytest modin/test/experimental/xgboost/test_default.py
          pytest modin/test/pandas/dataframe/test_binary.py
          pytest modin/test/pandas/dataframe/test_default.py
          pytest modin/test/pandas/dataframe/test_indexing.py
          pytest modin/test/pandas/dataframe/test_iter.py
          pytest modin/test/pandas/dataframe/test_join_sort.py
          pytest modin/test/pandas/dataframe/test_map_metadata.py
          pytest modin/test/pandas/dataframe/test_reduction.py
          pytest modin/test/pandas/dataframe/test_udf.py
          pytest modin/test/pandas/dataframe/test_window.py
          pytest modin/test/pandas/test_series.py
          pytest modin/test/pandas/test_rolling.py
          pytest modin/test/pandas/test_concat.py
          pytest modin/test/pandas/test_groupby.py
          pytest modin/test/pandas/test_reshape.py
          pytest modin/test/pandas/test_general.py
          pytest modin/test/pandas/test_io.py
          pytest modin/test/experimental/pandas/test_io_exp.py

  test-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    name: test docs
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          environment-file: environment-dev.yml
          python-version: 3.8
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Conda environment
        run: |
          conda info
          conda list
      - run: sudo apt update && sudo apt install -y libhdf5-dev
      - name: Docstring URL validity check
        run: python -m pytest modin/test/test_docstring_urls.py

  test-ray-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8"]
        test-task:
          - modin/test/pandas/dataframe/test_binary.py
          - modin/test/pandas/dataframe/test_default.py
          - modin/test/pandas/dataframe/test_indexing.py
          - modin/test/pandas/dataframe/test_iter.py
          - modin/test/pandas/dataframe/test_join_sort.py
          - modin/test/pandas/dataframe/test_map_metadata.py
          - modin/test/pandas/dataframe/test_reduction.py
          - modin/test/pandas/dataframe/test_udf.py
          - modin/test/pandas/dataframe/test_window.py
          - modin/test/pandas/dataframe/test_pickle.py
          - modin/test/pandas/test_series.py
          - modin/test/pandas/test_rolling.py
          - modin/test/pandas/test_concat.py
          - modin/test/pandas/test_groupby.py
          - modin/test/pandas/test_reshape.py
          - modin/test/pandas/test_general.py
          - modin/test/pandas/test_io.py
    env:
      MODIN_ENGINE: ray
      MODIN_MEMORY: 1000000000
      MODIN_TEST_RAY_CLIENT: "True"
    name: "test-ray-client"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          python-version: ${{matrix.python-version}}
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: pip install -r requirements-dev.txt --use-deprecated=legacy-resolver
      # Use a ray master commit that includes the fix here: https://github.com/ray-project/ray/pull/16278
      # Can be changed after a Ray version > 1.4 is released.
      - run: pip install https://s3-us-west-2.amazonaws.com/ray-wheels/master/c8e3ed9eec30119092ef966ee7b8982c8954c333/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
        if: matrix.python-version == '3.8'
      - name: Install HDF5
        run: sudo apt update && sudo apt install -y libhdf5-dev
      - run: python -m pytest ${{matrix.test-task}}
