name: push-to-master
on:
  push:
    branches:
      - master
concurrency:
  # Cancel other jobs in the same branch. We don't care whether CI passes
  # on old commits.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
env:
  MODIN_GITHUB_CI: true
jobs:
  test-ray-master:
    runs-on: ubuntu-latest
    defaults:
      run:
        # `shell: bash -l {0}` - special way to activate modin environment
        shell: bash -l {0}
    services:
      moto:
        image: motoserver/moto
        ports:
          - 5000:5000
        env:
          AWS_ACCESS_KEY_ID: foobar_key
          AWS_SECRET_ACCESS_KEY: foobar_secret
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mamba-env
        with:
          environment-file: environment-dev.yml
      - name: install Ray nightly build
        # Use --force-reinstall to always reinstall ray and its dependencies.
        # botocore isn't compatible with urllib3>=2; see #6094 for details
        run: pip install --force-reinstall "urllib3<2" https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl
      - name: Conda environment
        run: |
          conda info
          conda list
      - run: sudo apt update && sudo apt install -y libhdf5-dev
      - name: Run Modin tests
        run: |
          python -m pytest modin/tests/pandas/dataframe/test_binary.py
          python -m pytest modin/tests/pandas/dataframe/test_default.py
          python -m pytest modin/tests/pandas/dataframe/test_indexing.py
          python -m pytest modin/tests/pandas/dataframe/test_iter.py
          python -m pytest modin/tests/pandas/dataframe/test_join_sort.py
          python -m pytest modin/tests/pandas/dataframe/test_map_metadata.py
          python -m pytest modin/tests/pandas/dataframe/test_reduce.py
          python -m pytest modin/tests/pandas/dataframe/test_udf.py
          python -m pytest modin/tests/pandas/dataframe/test_window.py
          python -m pytest modin/tests/pandas/test_series.py
          python -m pytest modin/tests/numpy/test_array.py
          python -m pytest modin/tests/numpy/test_array_creation.py
          python -m pytest modin/tests/numpy/test_array_arithmetic.py
          python -m pytest modin/tests/numpy/test_array_axis_functions.py
          python -m pytest modin/tests/numpy/test_array_logic.py
          python -m pytest modin/tests/numpy/test_array_linalg.py
          python -m pytest modin/tests/numpy/test_array_indexing.py
          python -m pytest modin/tests/numpy/test_array_math.py
          python -m pytest modin/tests/numpy/test_array_shaping.py
          python -m pytest modin/tests/pandas/test_rolling.py
          python -m pytest modin/tests/pandas/test_expanding.py
          python -m pytest modin/tests/pandas/test_concat.py
          python -m pytest modin/tests/pandas/test_groupby.py
          python -m pytest modin/tests/pandas/test_reshape.py
          python -m pytest modin/tests/pandas/test_general.py
          python -m pytest modin/tests/pandas/test_io.py
          python -m pytest modin/tests/experimental/test_io_exp.py

  test-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    name: test docs
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mamba-env
        with:
          environment-file: environment-dev.yml
      - run: sudo apt update && sudo apt install -y libhdf5-dev
      - name: Docstring URL validity check
        run: python -m pytest modin/tests/test_docstring_urls.py
