name: ray-docker
on: pull_request
jobs:
  test-ray-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - shell: bash -l {0}
        run: docker build -f .github/workflows/ray-docker.dockerfile -t ray_docker_image:1.1.0 .
      - uses: addnab/docker-run-action@v2
        with:
          image: ray_docker_image:1.1.0
          run: |
            pytest modin/experimental/xgboost/test/test_default.py
            pytest modin/pandas/test/dataframe/test_binary.py
            pytest modin/pandas/test/dataframe/test_default.py
            pytest modin/pandas/test/dataframe/test_indexing.py
            pytest modin/pandas/test/dataframe/test_iter.py
            pytest modin/pandas/test/dataframe/test_join_sort.py
            pytest modin/pandas/test/dataframe/test_map_metadata.py
            pytest modin/pandas/test/dataframe/test_reduction.py
            pytest modin/pandas/test/dataframe/test_udf.py
            pytest modin/pandas/test/dataframe/test_window.py
            pytest modin/pandas/test/test_series.py
            pytest modin/pandas/test/test_rolling.py
            pytest modin/pandas/test/test_concat.py
            pytest modin/pandas/test/test_groupby.py
            pytest modin/pandas/test/test_reshape.py
            pytest modin/pandas/test/test_general.py
            pytest modin/pandas/test/test_io.py
            pytest modin/experimental/pandas/test/test_io_exp.py
